#!/bin/sh

source $(dirname $0)/vars

# start docker on the mac
# docker-machine start
dinghy up

# start db
docker run -d --name db \
  -v "/etc/postgresql" \
  -v "/var/log/postgresql" \
  -v "/var/lib/postgresql" \
  -p 5432:5432 \
  postgres:9.5.2
docker start db

# start redis
docker run -d --name redis \
  -p 6379:6379 \
  redis:2.8 \
  redis-server --appendonly yes
docker start redis

# rebuild the image
cd ~/sonar/$APP/docker
docker build -t local/$APP .

# remove the old image
docker rm -f $APP

# start the new image
docker run -d --name $APP \
  -v ~/sonar/$APP:/home/app \
  -p 3000:3000 -p 43828:43828 -p 8231:8231 \
  --link db:db \
  --link redis:redis \
  -e "SONAR_ENV=development" \
  -e "DATABASE_URL=$DATABASE_URL" \
  -e "RAILS_RESQUE_REDIS=$RAILS_RESQUE_REDIS" \
  -e "SECRET_KEY_BASE=$SECRET_KEY_BASE" \
  --dns 8.8.8.8 --dns 8.8.4.4 \
  local/$APP

# bundle install
docker exec $APP bundle install

# fire up bash
docker exec -it $APP bash -l

# ./thin
